### PR TITLE
Handle mdhd in version 1

### PR DESCRIPTION
**Pull request by Chocobozzz**
"if version is 1 then date and duration values are 8 bytes in length"

http://xhelmboyx.tripod.com/formats/mp4-layout.txt

### CODE REVIEW

**Comment by Chocobozzz** [comment]
@jhiesey Do you need help regarding this PR? For example a video file to reproduce the "bug" or anything else?

**Comment by jhiesey** [comment]
I'll take a look and merge asap. Thanks and sorry for the delay!

**Comment by Chocobozzz** [comment]
No worries, take the time you need :heart:

**Comment by jhiesey** [comment]
LGTM. Thanks!

**Comment by jhiesey** [comment]
Published as v1.2.0

**Comment by Chocobozzz** [comment]
Thanks!

**Pull request merged**
